### ISSUE TITLE
Stuck on IN_QUEUE

### ISSUE THREAD

**Issue by jimmy-desenio** [ashleykleynhans/runpod-worker-real-esrgan#1]
Hi,

Thank you for this package! 
I am encountering some issues, I am not sure if this is related to RunPod, or the handler. 

Steps to replicate the problem:

- Start a new serverless endpoint with the provided Docker image
- Send a request, it will sucessfully start and complete
- However when requesting status for the job, it will be stuck on IN_QUEUE

<img width="1353" alt="image" src="https://github.com/ashleykleynhans/runpod-worker-real-esrgan/assets/76520224/1e249164-fe42-4d41-8bf9-2bb6c3bfd944">
<img width="447" alt="image" src="https://github.com/ashleykleynhans/runpod-worker-real-esrgan/assets/76520224/a63fe58e-2e03-4e2f-b0c4-cf7e66749e36">

**Comment by ashleykleynhans** [comment]
Probably an issue with your max workers and/or GPU type selection, but either way its a configuration issue with your RunPod worker.  You can ask for assistance on Discord but its not a bug.
