### ISSUE TITLE
Other .pth models

### ISSUE THREAD

**Issue by TBS-CL** [ashleykleynhans/runpod-worker-real-esrgan#2]
Amazing code! But I can't seem to get any other .pth models to work, apart from what's bundled with the code. I'm not an expert in models so don't know if it's due to the new/old format incompatibility, or simply wrong parameters being passed.

The ones in particular I'm trying to use is: [https://nmkd.de/?esrgan](https://nmkd.de/?esrgan)
The error is something about: `model.load_state_dict(loadnet[keyname], strict=True) KeyError: 'params ......`

I'm trying with standard parameters:
```
model = RRDBNet(num_in_ch=3, num_out_ch=3, num_feat=64, num_block=23, num_grow_ch=32, scale=4)
netscale = 4
```

hilfe

**Comment by ashleykleynhans** [comment]
Unfortunately this uses Real-ESRGAN which only has support for its own models and not others, I also want to use other models but they load differently, so I'll look at creating a new version of this to support other models when I have a chance but don't have time right now.

**Comment by ashleykleynhans** [comment]
> Ok. Thank you! Looking forward that :) Maybe some code from this script can be handy: https://github.com/joeyballentine/ESRGAN/blob/master/upscale.py

I tried out this project but the quality of the result image was terrible.

**Comment by crapthings** [comment]
i try to make this work with 4x-UltraSharp.pth

I tried using this model 4x-UltraSharp.pth.
After commenting out this section of code, the image can be displayed, but the colors look incorrect.
If I disable the face enhance, the image does not display in normal colors.

<img width="618" alt="image" src="https://github.com/ashleykleynhans/runpod-worker-real-esrgan/assets/1147704/48e3e0cc-eb76-45a4-91c3-01983fb3da66">

<img width="562" alt="image" src="https://github.com/ashleykleynhans/runpod-worker-real-esrgan/assets/1147704/e7da9a28-6dca-4d11-8a3e-e067ff92e312">

**Comment by ashleykleynhans** [comment]
This uses Real-ESRGAN, only the Real-ESRGAN upscaling models are supported, not custom upscaling models.
https://github.com/xinntao/Real-ESRGAN
